### ISSUE TITLE
Moon and daylight glitches at night with latest version on 1.12

### ISSUE THREAD

**Issue by CcytherR** [CreativeMD/OpticManager#12] opened 2020-03-13 22:00 UTC
At night part of the moon flickers and glitches and whenever you open/close inventory or game menu daylight flickers glitches on/off for a moment. 

This is with the latest version of optic and creativecore on Minecraft 1.12.2.

Thanks.

**Comment by CreativeMD** [comment] 2020-03-16 22:01
I could not reproduce your issue. Would be helpful to know your configuration, what have you changed in which way?

**Comment by SeagalKru** [comment] 2020-03-17 20:47
I prepared a video of the bug. As soon as YouTube processes it, I'll drop the link here. Duration ~13 minutes and please watch until the end.
P.S.: https://www.youtube.com/watch?v=YZxeRt0UhZ4
P.S. №2: By the way. Previously, it was possible to change the cycle length of the day and night directly in the game by calling the GUI. And now, in order for the configuration changes to take effect, you need:
- in the single - go out and go into the world;
-on the server - restart the server.
Is it possible to return the GUI, or at least restart the config file through the console without restarting the server (without going to the world in the single)?

**Comment by tolerus** [comment] 2020-03-19 23:43
We're experiencing this as well; we'll see a bright flicker like in the youtube vid posted. We've noticed that the game will not let us go to bed to skip to day. We'll only see "Bed position set" prompt. When I issue the /time set 0 command we advance to day and the flicker seems to stop until the next night / moonrise. I've updated all of our creativemd mods at once with the creativecore 1.10.5 and the only setting in opticManager I've adjusted was setting the day and night lengths to 48000. We didn't experience this before the recent update. Hope this helps!

**Comment by CreativeMD** [comment] 2020-03-22 13:46
Can you try out the newest version of CreativeCore? Not sure but this might fix the issue.

**Comment by tolerus** [comment] 2020-03-22 17:36
The issue persists. An additional observation: we can sometimes advance
past night by sleeping in beds, but then after we skip to daylight the sun
is dusking in the west and in the flicker you can see the sun in the east,
like the correct morning time. It's like the sky is confused about what
time it's supposed to be and flickers at intervals of about a second to the
correct time and daylight brightness.

Thanks for looking into it!

**Comment by CreativeMD** [comment] 2020-04-02 13:39
Issue has been fixed in the newest version. I'm really sorry that it took me so incredible long to fix it. Hopefully everything works fine now.

**Closed as completed by CreativeMD** 2020-04-02 13:39 UTC

**Comment by SeagalKru** [comment] 2020-04-02 16:37
Unfortunately, the problem still remained ...

**Comment by CreativeMD** [comment] 2020-04-02 16:42
Oh right there was a second issue, released another new version which should fix that one as well.

**Comment by SeagalKru** [comment] 2020-04-02 16:52
Hmm ... Checking ... Wait. :)

**Comment by SeagalKru** [comment] 2020-04-02 17:01
Excellent! Fixed! Nice! Many thanks to you!

But I would like to consult with you on a less significant problem.
Can you advise a mod (with courseforge) that will replace the function of the button for switching the crafting option that was in the IGCM? She can not be done only in OpticManager?

It is also impossible to make a GUI right in the game itself to adjust the duration of the day and night cycle, so as not to do this in the config file with restarting the world?

**Comment by CreativeMD** [comment] 2020-04-02 17:12
I don't think anybody else has implemented a feature like this and I also don't plan to use it further sorry.

You can type in /cmdconfig for that.

**Comment by SeagalKru** [comment] 2020-04-02 17:17
Hah How simple it all turned out! But is it possible to bind this command to the button so that less time is spent on calling the GUI menu? ;)
It is a pity that you will not enter the deleted function. But in any case, thanks for the work done to fix bugs!

**Comment by tolerus** [comment] 2020-04-03 15:05
Excellent! Thanks! You make the best mods :)
