### ISSUE TITLE
Comfort's Hammocks [1.12.2]

### ISSUE THREAD

**Issue by Sereath** [CreativeMD/OpticManager#15] opened 2022-03-03 18:25 UTC
Sorry to bother you with 1.12 but I thought it was worth a try after failing to find a solution.

I have a similar issue to this one when using the Hammocks from Comforts. For context, hammocks are supposed to allow you to sleep during the day until the beginning of the night:

https://github.com/TheIllusiveC4/Comforts/issues/10

https://www.curseforge.com/minecraft/mc-mods/comforts

So the issue is that using hammocks at any time during the day moves the time to the morning, instead of the twilight/evening. Meaning that players can easily skip the nighttime danger at really any point during the day and that compromises a very large facet of a modpack I've been developing for some years now.

https://youtu.be/TDVAI7smtmc

I did not know of this unintended mod interaction until I finally started playtesting with people in a server a month ago.

**Comment by CreativeMD** [comment] 2022-03-04 11:27
Unfortunately I have dropped support for 1.12 entirely, so I can't help you directly. But this mod is open source and maybe someone else can attempt to fix it. OpticManager adapts to a new time, if there is a jump. For example when you sleep in bed during the night, it tries to take the new time and assign it to changed day & night cycle. However, the system is not perfect. I have no clue why it does not work in this case. Probably depends on how the other mod adds the time to the world and how OpticManager is configured.

Maybe you can ask the author of comforts to make changes to his code so that OpticManager does not interpret things wrong. The mod could even try to modify the time of OpticManager directly. I can of course help out and explain how the code works, but I will not work on the actual mod for 1.12.

If this issue occurs in 1.18 and I will try to fix it. But so far nobody has ever reported an issue like that. So I cannot reproduce the situation and figure out a solution.

Sorry for the inconvenience.

**Closed as completed by CreativeMD** 2022-03-04 11:27 UTC
